### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Zekken01** [Barteks2x/CubicChunks#125]
I'm having this happen when I try to build.
https://u.nya.is/eolczk.png

**Comment by Niko-sk2x** [comment]
1. provide full build log, not a screenshot
2. How exactly are you building it? Did you run `gradlew setupDecompWorkspace` before?
3. Which branch are you building?

**Comment by Zekken01** [comment]
I got it working.

**Comment by JonL98** [comment]
How does one build this anyway? I've compiled mods with Forge before, but it's been a while.

**Comment by Niko-sk2x** [comment]
As of the most recent commit you need to clone the repository including submodules:
`git clone --recursive https://github.com/Barteks2x/CubicChunks.git`, and then:

 1. If you want to use it within any IDE: `gradlew serupDecompWorkspace`, otherwise skip this step
 2. If you want to build it: `gradlew build` should work (and yes, it should work even if you didn't run setupCI/Decomp/DevWorkspace, travis CI build does just gradlew build)

On linux (and probably mac) replace `gradlew` with `./gradlew`.

Also note that you probably shouldn't use this mod yet, especially if you care about your worlds. Even after world format change there are still more changes planned, related to how lighting data is stored.

**Comment by JonL98** [comment]
Thanks. I always create new test worlds for this kind of stuff anyway. Actually, I was going to try it's compatibility with WorldPainter maps that exceed the normal block limit, which brings up another point. 
When this mod is operational, you should talk to the developer behind WorldPainter. It would be pretty neat to see direct compatibility between CubicChuncks and WorldPainter.

**Comment by Niko-sk2x** [comment]
I'm almost sure way back in 1.6.4 I got PM from developer of such mod about compatibility, so if what I remember is right, they should be interested.
