### ISSUE TITLE
compiled it

### ISSUE THREAD

**Issue by notoriousgtw** [Barteks2x/CubicChunks#2]
I compiled the repo then attempted to run it in mine craft but i crashed almost immediately

log: [http://paste.ee/p/BUY3o#](url)

**Comment by Barteks2x** [comment]
I see you tried to run it in "real" environment (I usually run it from IDE). I probably forgot to shade some library.

Also, before you ask for support - try to run it without any other mods. Especially Optifine/FastCraft.

Also note that there is a reason why I didn't release it yet. World wormmat is almost guaranteed to change in way that it will be incompatible with previous format before release (and there will be no converter, because there was no release). There are also some serious performance issues.

**Comment by notoriousgtw** [comment]
Thank you, I'll attempt to run it in clean environment from ecclipse.
Also, I'd love to help with development, as I'm very interested in deep modification of the base game, though im not super-profficient in java.

**Comment by Barteks2x** [comment]
I still need to work on my wiki pages, I will try to update them today. You should be able to find useful information there. I could write it all here but there is no point in repeating that information.

If you want to run it in dev environment here is list of JVM arguments I would recommend:
`-Dfml.coreMods.load=cubicchunks.asm.CoreModLoadingPlugin -Xmx2G -ea -XX:-OmitStackTraceInFastThrow -Dmixin.debug.verbose=true -Dmixin.debug.export=true`
Only the first argument is required to run the mod (only required in dev environment, in production environment forge reads MANIFEST.MF from jar file). I would also suggest using IntelliJ IDEA instead of eclipse to avoid issues with code formatting (there is intellij ide aformatter settings file in this repository).

I will update the code to work outside of dev environment as soon as I finish my work on new generation pipeline (this is what causes performance issues I mentioned).

As for your question about learning more about modding - github issue isn't a good place to discuss it but I will answer anyway.

If you want to learn modding - I would suggest trying to actually write some mod. There is no easy way around it (I assume you already know java). You can also join #minecraftforge channel on EsperNet on IRC if you aren't there already.

If you want to learn things specifically useful for Cubic Chunks mod development - you can play around with the code, and try to understand it. Reading [Mixin wiki](https://github.com/SpongePowered/Mixin/wiki) may also be very useful when trying to understand how code in cubicchunks.asm.mixin package works (and why I can cast World to ICubicWorld).

**Comment by notoriousgtw** [comment]
okay thank you and ill use idea to decompile and run it.

**Comment by Barteks2x** [comment]
Fixed in https://github.com/Barteks2x/CubicChunks/commit/7b1e514411f0a9e69c6a9662544a521851a47c90
