### ISSUE TITLE
Mekanism doesn't work with CC

### ISSUE THREAD

**Issue by BaccarWozat** [Barteks2x/CubicChunks#200]
Since Mekanism is brand new for 1.11.2, this is actually expected behavior. Anyway, I ran it for both CC-Vanilla and CC-Custom and it won't get past the Loading World screen.

Error log (CC Vanilla): https://pastebin.com/XyvJLKwh
Error log (CC Custom): https://pastebin.com/AgUA0v6w
Latest log (CC Vanilla): https://pastebin.com/11nYhi1i

Using CC 781, Forge 2308, Mekanism 9.3.0

**Comment by Niko-sk2x** [comment]
I could try to fix it, but it's going to be a hack and some parts of mekanism probably aren't going to work anyway.

This mod seems to work directly with chunks. And it directly accesses the tile entity hash map to clone it and go through all tile entities and do some compatibility registration. It's not going to work. I will look into how Mekanism could do the same thing so that it works both with vanilla and Mekanism.

**Comment by Niko-sk2x** [comment]
I do have an idea for a fix, but it would be mod-specific workaround. And I'm not sure if some other part of mekanism won't break then.

**Comment by Niko-sk2x** [comment]
Fixed on mekanism side
