### ISSUE TITLE
Render issue with LittleTiles

### ISSUE THREAD

**Issue by CreativeMD** [Barteks2x/CubicChunks#314]
Hey there,
i'm the author of LittleTiles and recently somebody an issue:

LittleTiles blocks don't render above 256 or below 0:
![](https://cdn.discordapp.com/attachments/276752435869908993/387026096685580298/2017-12-04_3.png)

LittleTiles uses a rather hacky way to save performance. It hooks into the `ChunkRenderDispatcher` and adds the render data once minecraft uploads the buffer to the graphic card. [Source](https://github.com/CreativeMD/LittleTiles/blob/1.11.2/src/main/java/com/creativemd/littletiles/client/render/LittleChunkDispatcher.java#L120).

Maybe we can figure out a solution together. How does CubicChunks render its chunks? Is there a way for me to hook in?

In Regards
CreativeMD

**Comment by Niko-sk2x** [comment]
CubicChunks renders chunks exactly the same way as vanilla Minecraft does. It's close enough that optifine required only one patch to get entity rendering working and everythinbg else worked fine.

After looking at the code, I belive this is the issue: https://github.com/CreativeMD/LittleTiles/blob/6a58ecc7506c3d29616fabbe62748372a8c67113/src/main/java/com/creativemd/littletiles/client/render/RenderUploader.java#L258-L308
specifically: https://github.com/CreativeMD/LittleTiles/blob/6a58ecc7506c3d29616fabbe62748372a8c67113/src/main/java/com/creativemd/littletiles/client/render/RenderUploader.java#L288

Cubic chunks modifies the way it's calculated: https://github.com/OpenCubicChunks/CubicChunks/blob/00804e89b36141af5ed35bece960543b40ccb8d8/src/main/java/cubicchunks/asm/mixin/core/client/MixinViewFrustum_RenderHeightFix.java#L109-L134

You should be able to fix the issue by reflectively calling that viewfrustum method, instead of (stil half- reflectively) reimplementing it yourself

**Comment by CreativeMD** [comment]
Oh, the RenderUploader is inactive, it was just a test to modify the render data after it has been uploaded, but i threw away this idea.

**Comment by Niko-sk2x** [comment]
Well then I will have to look at the code again

**Comment by Niko-sk2x** [comment]
Or is it *really* inactive?

[This method](https://github.com/CreativeMD/LittleTiles/blob/6a58ecc7506c3d29616fabbe62748372a8c67113/src/main/java/com/creativemd/littletiles/client/render/RenderUploader.java#L258-L308) is used [here](https://github.com/CreativeMD/LittleTiles/blob/4d7fc7e49e4d474227ca0c3abd95aa57af25c760/src/main/java/com/creativemd/littletiles/client/render/RenderingThread.java#L74), which is used:
 * [here](https://github.com/CreativeMD/LittleTiles/blob/44e9ee021caa21cbeca79a7d364baffc9129671f/src/main/java/com/creativemd/littletiles/common/tileentity/TileEntityLittleTiles.java#L415) which is used in enough places that if it's all dead code, I'm going to seriously question the quality of your code
 * [here](https://github.com/CreativeMD/LittleTiles/blob/09e463d169514129d6dd0ba8e5264c0a2f9f834b/src/main/java/com/creativemd/littletiles/common/entity/EntityAnimation.java#L272), no idea what it's for
 * [here](https://github.com/CreativeMD/LittleTiles/blob/09e463d169514129d6dd0ba8e5264c0a2f9f834b/src/main/java/com/creativemd/littletiles/common/entity/EntityDoorAnimation.java#L86), also no idea what it's for

That seems to be far from dead code

**Comment by CreativeMD** [comment]
Oh sorry ... i was not really paying attention to be honest. I will try to fix it. Thanks for all your help and again sorry :(

**Comment by CreativeMD** [comment]
Unfortunately things are not fixed, but it's better already.
![](https://i.imgur.com/u7ySsdB.png)
![](https://i.imgur.com/mX90joI.png)

So everything between 0 and 527 renders correctly. No idea why this is the case, but maybe you have an idea?

EDIT
Maybe because i was still using the old method ... i created a fix for it, but forgot to link to the new method.
Anyway it is fixed now! Thank you very very much for your help!!!
