### ISSUE TITLE
Only generate needed chunks

### ISSUE THREAD

**Issue by sirati** [Barteks2x/CubicChunks#353]
Limit chunk generation to chunks actually needed. i.e. use ray tracing to find out which chucks are visible or are going to become visible soon. 

This would drastically reduce the lag caused by people rapidly exploring the world. Would also reduce save filesize.

Problems:
- Chuck population may be problematic
- Spectators would not be able to see much when diving through underground.

**Comment by Niko-sk2x** [comment]
This is not viable to do server side.

As it is it would actually increase server lag. Raytracing is very expensive operation. That's why Minecraft never uses it. Clientside it uses a simplified visibility graph algorithm. But even that would not scale well to tens or hundreds of players, even when they are in very small area. 

It would also lead to something very counterintuitive: Plant and animals not in view may not update. Players definitely wouldn't like it.

Another option would be to let clients request chunks to be loaded. This could work but it would be a very significant change that would break even more mods.
Many mods rely on all the chunks near a player being loaded to work correctly. Even the openblocks elevator mod - it requires both elevator endpoints to be loaded clientside.

And all of the above ignores the fact that it's just not something I want to do in this mod. There has to be a limit to what this mod does. The idea is to keep things similar to vanilla. I made a big exception for CustomCubic world type, which will be a mod on it's own, to avoid adding unnecessary things to the base cubic chunks mod.
