### ISSUE TITLE
Aether 2

### ISSUE THREAD

**Issue by Sephiroth91** [Barteks2x/CubicChunks#436]
Hello,

if I use the last version of curseforge, the client crashed while generating a new world . If I use the latest  code of github the client crashs by game start directly. I use the latest Aether2 version and Forge 2768.

[crash-2019-03-30_22.15.52-server_create_world.txt](https://github.com/OpenCubicChunks/CubicChunks/files/3025976/crash-2019-03-30_22.15.52-server_create_world.txt)
[crash-2019-03-30_22.19.50-client_load_clientt.txt](https://github.com/OpenCubicChunks/CubicChunks/files/3025977/crash-2019-03-30_22.19.50-client_load_clientt.txt)

**Comment by Niko-sk2x** [comment]
Phosphor will never be compatible with CC. CC has it's own lighting propagation system (currently unfinished).

There also seems to be some orbis related issue that is actually CC fault. This will be fixed. 

Nothing in the logs indicates any issue with Aether. Can you try to get a minimal set of mods that still had that issue and upload debug.log?

**Comment by Sephiroth91** [comment]
I have use only the aether mod by the uploaded log. Orbis is together with the aether mod in only one .jar

**Comment by dunnousername** [comment]
FWIW:

I've never used Aether (or Aether 2) before. But, I was wandering around github, and I found that Phosphor mod's repo [this link](https://github.com/jellysquid3/Phosphor). I also found [this graph](https://raw.githubusercontent.com/jellysquid3/Phosphor/master/doc/benchmarks.png) which includes Aether 2. There's a benchmark with and without Phosphor for Aether 2, which suggests that maybe (maybe wrong here) Phosphor is included when you download the Aether 2 mod jar (so it can be removed), and, besides Orbis stuff (unless that is fixed), if you somehow remove Phosphor, Aether 2 could work.

P.S. I just downloaded the artifact from the Jenkins CI. Looks like they include Orbis and Phosphor inside the JAR. I haven't tested it, but maybe removing those jars from the Aether 2 jar would make it work? I'll try it.

![image](https://user-images.githubusercontent.com/12957182/59643734-d9834b80-9137-11e9-8065-a8e7f43bc649.png)

**Comment by Niko-sk2x** [comment]
I remember some discussion about it happening on my discord too where we found that Aether essentially includes phosphor, and that removing Phosphor from aether by editing the jar file, manifest.mf and removing jar signing data made it work.

**Comment by dunnousername** [comment]
I thought I'd try that quickly by just removing the jars inside. I removed both but then MC got upset since there was no Orbis, so I added Orbis and it got upset since there was no Phosphor after that. So I guess you do have to edit the manifest.mf and jar signing. That is pretty cool, though, considering that no code changes are needed for a mod like the Aether 2; one that directly affects worldgen and adds a new dimension. I do wonder though (and I've never played Aether 2), I thought if you were to fall off the edge, it would bring you back to the overworld. I wonder if that mechanic is at all broken when using cubicchunks...

**Comment by Niko-sk2x** [comment]
I remember testing both existing aether mods with cubic chunks at some point and as I remember, both teleported you to y=256 just fine. It just can be a bit dangerous with CC because there may actually be blocks up there.
But I did those tests long time ago and things may have changed.

To make forge not complain about missing phosphor you have to remove contained deps line from manifest.mf (or edit it. And it may be 2 lines, split in an arbitrary-looking way). And as I said, remove jar signing data

**Comment by jellysquid3** [comment]
Hello! I'm the Technical Lead at Gilded Games, the team that works on the Aether II.

As noted, we make use of JAR signing for all our releases, which makes disabling Phosphor a bit difficult. However, you _can_ modify the configuration file for Phosphor (which can be found under the `phosphor.json` file in your `config` directory) and set `enable_phosphor` to `false`. This will prevent Phosphor from applying any transformations and should allow things to work with OpenCubicChunks.

If you do not have this config entry, please make sure you are using the latest release of Phosphor or the Aether II and try deleting the config file to have it populated with new default values upon game startup.

**Comment by Niko-sk2x** [comment]
Since this was actually a phosphor issue, and not aether, closing.
