### ISSUE TITLE
[1.12.2] Auto Disabling

### ISSUE THREAD

**Issue by GamingInfinite** [Barteks2x/CubicChunks#452]
When The game is loading, (through twitch mind you), it says that it loads cubic, but then in the mods list it says it is disabled, and I can't figure out how to fix said issue.  I'd really like to try and include this in the modpack I'm creating w/ my friends but it isn't working and I don't know why.

**Comment by Niko-sk2x** [comment]
Ignore it, it's a result of an unfinished piece of code I started on to split coremod and mod into separate jars. This turned out to be impossible, but the beginning of code to show coremod as separate entry in modlist remained, and I never added code to list it as "enabled". It's really just a fake mod entry that doesn't do anything. When creating a new world, in world options, select "CubicChunks: Yes" and it should work (or use CustomCubic world type from CubicWorldGen)

In the unlikely case I'm wrong here and the mod really does get disabled (it shouldn't be possible), reply here and I will look into it.

**Comment by GamingInfinite** [comment]
One question, can Cubic be used with another world gen like biomes o plenty or biome bundle, because that's what I'm trying to do.  I thought it just removed top and bottom?

**Comment by Niko-sk2x** [comment]
CubicChunks itself will work on Biomes o plenty. BiomeBundle is a bit of an issue for various technical reasons due to how OTG works. CubicWorldGen obviously can't because it's a separate world type.
