### ISSUE TITLE
Minecraft coordinates are real numbers- not intergers.

### ISSUE THREAD

**Issue by LiEnby** [Barteks2x/CubicChunks#466]
Minecrafts coordinates are stored as 'real' numbers (as defined by the IEEE 754-2008) - not intergers so your claim "This MinecraftForge mod extends Minecraft height and depth. The only limitation is size of 32-bit integer." is wrong the actural limitation is the maximium float value of -Inifinty to +Infinity (or 1.175494351 E - 38 to 3.402823466 E + 38)

**Comment by Niko-sk2x** [comment]
You are right but also wrong.

Minecraft **entity** coordinates are floating point numbers. Specifically, double precision floating point numbers.
Rendering is done with single-precision floating point numbers (with clever tricks to keep the numbers involved reasonably small at huge coordinates in most cases).

**Block** and **Tile Entity** positions are 32-bit integers. **Chunk positions** are also 32-bit integers. Since 32-bit integers have smaller value range than double precision floating point numbers, they are the limitation.
