### ISSUE TITLE
Crash when used with JustEnoughIDs-1.0.3-48

### ISSUE THREAD

**Issue by ThunderwolfPony** [Barteks2x/CubicChunks#493]
[crash-2020-04-11_17.42.32-client.txt](https://github.com/OpenCubicChunks/CubicChunks/files/4465592/crash-2020-04-11_17.42.32-client.txt)
[latest.log](https://github.com/OpenCubicChunks/CubicChunks/files/4465594/latest.log)

**Comment by ThunderwolfPony** [comment]
Turns out, they just uploaded an update that fixed the compatibility problem

**Comment by Niko-sk2x** [comment]
Don't use JEID with CC. This will appear to work but unless you are fully aware of how it works, how it interacts with CC and the limitations it WILL break your world and there will be no recovering it. 

NEID is actually supported on CC and works almost equally well.

**Comment by ThunderwolfPony** [comment]
Wait, does it matter if your starting a new modpack with only CC and JEID?

Edit: Also I've had lots of problems with NEID causing lots of incompatibility

**Comment by Niko-sk2x** [comment]
What exactly are the NEID compatibility issues? Noone has ever been able to show me even one.

And what matters here is that JEID is removing ID limit restrictions, but CC is still overwriting the chunk saving code in a way that JEID can't detect. So while the registration becomes unrestricted, the chunk saving still had the limits and will break if you actually run out of the limits. This will still work for block IDs because NEID-specific code will trigger in CC, but for things like biomes, it will just get corrupted.

**Comment by ThunderwolfPony** [comment]
I've tried to get a reasonable crash or log file with NEID, but the game just loads forever then closes. With JEID I at least get to see the crash or log file

**Comment by Niko-sk2x** [comment]
Again I didn't ever have anyone show me such a caee. A list of mods and a world file if not only happens with an existing world. Or instructions which mods to add and remove in which order. 

As far as I can tell NEID and JEID work in largely the same way but NEID is far less significant change to world save format so I can support that in CC.

**Comment by sa-shiro** [comment]
NEID works just fine and i never had any crashs or issues with it in combination with CC and lots of other mods tho i wouldnt recommend JEID, because it changes **alot**

If your game crashes with having it installed (NEID), you may got a broken minecraft installation / mods and also try to update your forge, 2847 is outdated, newest is 2852
