### ISSUE TITLE
Customizable worldgen for nether.

### ISSUE THREAD

**Issue by RealXuChe** [Barteks2x/CubicChunks#497]
In the current version, although nether's height restriction has been removed, its generation algorithm is still vanilla. No structure will be generated above about y=200 except endless netherracks.
Please add a setting menu for customizing nether worldgen.
English is not my native language, if you find a grammatical or spelling error, please tell me to correct it.

**Comment by sa-shiro** [comment]
Copy a custom preset into `/DIM-1/data/cubicgen/custom_generator_settings.json`
(This folder also includes the default preset for the nether)

Structures are currently not supported except for strongholds and nether fortresses. (Afaik only within vanilla range)


If you want to customize nether: copy the content of the preset into the CWG GUI, change it to your needs and copy it back to the preset file

**Comment by RealXuChe** [comment]
On my computer, by default, there isn't the directory `DIM-1/data/cubicgen`.
I created the directory and copied `data/cubicgen/custom_generator_settings.json` to `DIM-1/data/cubicgen`, but it didn't work.
I'm currently using these mods:
`CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all`
`CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all`
`malisiscore-1.12.2-6.5.1`
`OptiFine_1.12.2_HD_U_F5`
`forge1.12.2-14.23.5.2768`
Am I doing anything wrong?

**Comment by sa-shiro** [comment]
Edit:
I totally forgot that hybridworld enables the use preset for all dimensions, so the nether is not from CWG xD you have to install the hybrid world mod to use presets for the nether 

====
It seems like your nether is excluded to be cubic
Check your cubic chunks mod settings if -1 is in the blacklist

CubicWorldGen will automatically create this folder and the preset, if no one has been defined (as long as it's not blacklisted and for nether, you need to enter the nether first to generate them)


If the nether is excluded / vanilla, you have to delete the region folder (a cubic world can be identified by 2 region folders (2d and 3d)) or use the converter tool available on the discord (I never used it, so idk much about it)


Edit:

Please do not use the overworld preset (data/cubicgen/...) Because it's totally different to the nether one

**Comment by RealXuChe** [comment]
emm....
After searching, I can only find the source code of `HybridWorld` [here](https://github.com/Foghrye4/HybridWorld).
I didn't find a prebuild jar file of this mod. Can you please tell me where I can find it, or there isn't a prebuild jar file?

**Comment by sa-shiro** [comment]
Available at the cubic chunks discord or compile it yourself

**Comment by RealXuChe** [comment]
Solved.
