### ISSUE TITLE
Game seems to crash, and im running out of ideas.

### ISSUE THREAD

**Issue by Official-Husko** [Barteks2x/CubicChunks#504]
First of all thanks for you work, i appreciate it. Now, im currently making a modpack for me and my friends but since im upgrading my pc and waiting for a replacement mobo i cant use my main pc so im using my laptop so don't cry when you see awfull specs. (Not meant rude)

When i im creating a new world and when i enable the CubicChunks mod with the setting "Default" i can't get into the world because it always crashed as the end. Here are the Logs

[Grash Log 1](https://cryptobin.co/b097d955) Password: 1234567890
[Crash Log 2](https://pastebin.com/WVYGwMWm)

**Comment by Niko-sk2x** [comment]
I see several issues even before getting to the crash just by looking at the log:

```
| LCHIJA | otgcore                     | 1.12.2 - v8.3              | minecraft.jar                                             | None                                     |
| LCHIJA | openterraingenerator        | v8.3                       | OpenTerrainGenerator-1.12.2+-+v8.3.jar                    | None                                     |
```
OTG is generally known to not work well with cubic chunks.

```
| LCHIJA | chunkpregenerator           | 2.1                        | Chunk+Pregenerator+V1.12-2.2.jar                          | None                                     |
```
useless with cubic chunks

```
| LCHIJA | dsurround                   | 3.6.1.0                    | DynamicSurroundings-1.12.2-3.6.1.0.jar                    | 
```
DynamicSurroundings is knownt o have some issues. There is a configuration that works but I'm not fully up to date on what exactly it is.

```
| LCHIJA | farseek                     | 2.5                        | Farseek-1.12-2.5.jar                                      | None                                     |
```
CubicChunks breaks some of this

```
| LCHIJA | streams                     | 0.4.8                      | Streams-1.12-0.4.8.jar                                    | None                                     |
```
this is not going to work.


The actual error you are getting is caused by some modded generator doing something unexpected in early chunk generation stage and cubic chunks optimization breaks it. It can be disabled. Just disable `optimizedCompatibilityGenerator` in cubic chunks config.

There are also several mods that I see for the first time and I have no idea whether cubic chunks is compatible with them.

Also avoid using such weird paste sites... you are just making things unnecessarily complicated.
