### ISSUE TITLE
compatibility with command-o-matic

### ISSUE THREAD

**Issue by sazuko07** [Barteks2x/CubicChunks#533]
issue lies with filling blocks below y-coordinate 0 or above y-coordinate 255. throws error of "cannot place blocks outside of the world", when i am able to place single blocks of any kind above or below that threshold. fill command becomes useless "below" or "above" the original build ceiling or floor.

**Comment by KandiPanda** [comment]
The issue is in Command-O-Matic rather than in Cubic Chunks, but I submitted a PR to Command-O-Matic that _should_ fix it anyways. (If they don't merge the PR and upload a new build to CurseForge, you should still be able to build the fork I did the PR with for yourself.)

**Comment by NotStirred** [comment]
https://github.com/vova7865/command-o-matic/pull/1 closes once PR is accepted - Tested and working with CC

**Comment by sazuko07** [comment]
thank you for the quick reply and the hard work! i think this may solve the issue, but my java compiler (javac) gets errors (70 of them) when i try to recompile the java files back into its classes. If you could compile the javas or point me toward a resource that works to compile these minecraft java files, that would be very much appreciated.

**Comment by Shad0wlife** [comment]
Ok, this really has nothing to do here - since the others already pointed out that this was an Issue in command o matic, but I'll just answer for the sake of helping:

Set up a forge MDK environment, put the files of the whole repo of command o matic in the folders of the same names, and use the build system of forge.
Please read some tutorials on forge modding on how to set it up exactly.

Alternatively you could just wait for an update of command o matic since Kandi's changes got merged.

**Comment by ghost** [comment]
@sazuko07 merged, updated the file on curseforge. thanks @KandiPanda !
