### ISSUE TITLE
Rename CubeCoords to CubePos

### ISSUE THREAD

**Issue by kashike** [Barteks2x/CubicChunks#86]
`ChunkPos` is the same of the object in vanilla Minecraft used to represent a `Chunk`'s position (x, z). Renaming `CubeCoords` to `CubePos` would keep it consistent, and give it a slightly nicer looking name.

**Comment by Cyclonit** [comment]
I do agree that its nice to have consistency, but this would be a massive refactor with very little benefit.

**Comment by Barteks2x** [comment]
That would be nice together with other mass renaming, maybe together with changing names to be similar to MCP names.

**Comment by Boreeas** [comment]
Copying this here because apparently Github swallowed my email reply:

It wouldn't be too bad, I think. IDEA will rename it for you safely, and
we don't really need to do a code review on a simple rename. Maybe we
could combine it with all the other formatting and renaming changes we
still had planned.

I suppose we should start making a list?

- [ ]  `CubeCoords` -> `CubePos`
- [ ]  `CubeCoords.getCube{X,Y,Z}` -> `get{X,Y,Z}`
- [ ]  Mass-Reformat the entire project according to our formatting settings

**Comment by Cyclonit** [comment]
I would also rename "PlayerCubeMapEntry" to "CubeWatcher" and "PlayerCubeMapColumnEntry" to "ColumnWatcher". I do not see the advantage in keeping them named this way. Methods using them are long an unwieldy, cluttering up classes and ultimately hurting readability and maintainability.

**Comment by Barteks2x** [comment]
[List of planned changes](https://gist.github.com/Barteks2x/0efcbae64b926be17259959f28a075fe)

**Comment by Boreeas** [comment]
It wouldn't be too bad, I think. IDEA will rename it for you safely, and
we don't really need to do a code review on a simple rename. Maybe we
could combine it with all the other formatting and renaming changes we
still had planned.

Am 21/10/2016 um 12:21 schrieb Cyclonit:
> I do agree that its nice to have consistency, but this would be a massive refactor with very little benefit.
>
